template = "https://github.com/giellalt/template-lang-und"
rev_id = 262
template_sha = "e76bfc45ca43118d648ca429564512658ac2ea78"

[replacements]
__GLOTTOLOG_ID__ = "ston1242"
__REPO__ = "lang-sto"
__UND2C__ = "sto"
__UNDEFINED__ = "Stoney"
__UND__ = "sto"
