template = "https://github.com/giellalt/template-lang-und"
rev_id = 254
template_sha = "9eb2a95995f59cb63a159a5cc7bcce8f049babe4"

[replacements]
__GLOTTOLOG_ID__ = "ston1242"
__REPO__ = "lang-sto"
__UND2C__ = "sto"
__UNDEFINED__ = "Stoney"
__UND__ = "sto"
