template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "ston1242"
__REPO__ = "lang-sto"
__UND2C__ = "sto"
__UNDEFINED__ = "Stoney"
__UND__ = "sto"
